export { createApp } from './src/creatApp'
export { h } from './src/h'
export { getCurrentInstance } from './src/component'
export { createTextVNode } from './src/vnode'
export { renderSlots } from './src/helpers/renderSlots'
